all:
	#gcc -o hello -L. -lcontrolcan -lpthread -lusb main.c
	#arm-none-linux-gnueabi-gcc -o hello -L. -L /home/pi/Public/linuxCan/controlcan -lcontrolcan -lpthread main.c
	g++ -o hello_cpp main.cpp /home/pi/Public/linuxCan/controlcan/libcontrolcan.so  -lpthread 

clean:
	rm -f *.o hello
